# .cargo/config.toml
# DOCS: ./CARGO_PROFILING.md

[build]
### $ cargo clean; time cargo build --timings
# jobs = 8  # (default)  350.0s (5m 50.0s) | 407.4s (6m 47.4s) | 283.9s (4m 43.9s)
# jobs = 8  # --release  153.0s (2m 33.0s) | 158.9s (2m 38.9s)
# jobs = 1  # 1456.7s (24m 16.7s)


## mold is a faster linker - https://github.com/rui314/mold
## $ readelf -p .comment target/release/fractals
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=--ld-path=/usr/bin/mold"]