# Example: https://github.com/letsgetrusty/example_lib/blob/master/.github/workflows/rust.yml
# Example: https://www.youtube.com/watch?v=bw_kseQYxto&ab_channel=Let%27sGetRusty

name: Rust

on:
  push:
    branches: [ "master", "yew" ]
  pull_request:
    branches: [ "master", "yew" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
                    
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run clippy
      run: cargo clippy
